### ISSUE TITLE
Could not use lib

### ISSUE THREAD

**Issue by uatach** [Kerosene2000/random-wheel-rs#1]
I've added dependencies in Cargo.toml: `random-wheel = "*"`
and `use`ed: `extern crate random_wheel; use random_wheel::*;`
saying:
error: import `random_wheel` conflicts with imported crate in this module (maybe you meant `use random_wheel::*`?) [E0254]

am I doing something wrong?

**Comment by Kerollmops** [comment]
Try to use directly.
`use random_wheel::RandomWheel;`
But I didn't test it in an extern project, I will try today maybe. And when I will know how to push documentation on my github domain name I will do it.

Say me if it works, that I can close this thread ;)

**Comment by uatach** [comment]
Didn't work:
error: unresolved import `random_wheel::RandomWheel`. There is no `RandomWheel` in `random_wheel`

**Comment by Kerollmops** [comment]
commit hash: fa3ee81be364b028d90e28898277be31bd667bcd
fix the error thanks to you and sorry :+1:
