### ISSUE TITLE
Keep `ref` or not ?

### ISSUE THREAD

**Issue by Kerollmops** [Kerosene2000/random-wheel-rs#4]
Did I change the `RandomWheel` implementation:

``` rust
// from
push(&mut self, proba: f32, data: &'a T)
// to
push(&mut self, proba: f32, data: T)
```

And if I do this can people use `Box` or `Struct with an &T` ?

**Comment by uatach** [comment]
I think the change is a good idea, and I'm guessing that there would be no problem while an instance of wheel don't go off scope.

**Comment by Kerollmops** [comment]
yup, I am working on this, the changes will probably be applied in some hours (2, 3), 6e18e89028ea17ea384e369badda8ebf61b54c6a

**Comment by Kerollmops** [comment]
and it works well (I think) d256fec
