### ISSUE TITLE
Docs site leads to 404

### ISSUE THREAD

**Issue by dashed** [Kerosene2000/random-wheel-rs#8]
The link on the README leads to a 404 page: https://kerosene2000.github.io/random-wheel-rs-doc/random-wheel-rs/random_wheel/index.html

**Comment by Kerollmops** [comment]
You should go on http://docs.rs to see thereal doc, I will update that, thanks for the report.

**Comment by Kerollmops** [comment]
https://docs.rs/roulette-wheel/0.2.2/roulette_wheel/

**Comment by dashed** [comment]
@Kerollmops thanks!
